### ISSUE TITLE
Sprite not displayed in 3.6.2

### ISSUE THREAD

**Issue by saghoti** [iwae/Cocos-SpriteSheet-Animator#1]
Hello, thank you very muck for creating such a fantastic and convenient component for sprite sheet animation.

I am currently using this component under creator 3.6.2 and running it without any errors.
However the images are not being displayed (as shown in the picture)
<img width="1038" alt="截圖 2023-05-16 下午1 29 15" src="https://github.com/iwae/Cocos-SpriteSheet-Animator/assets/50196560/dc77c085-486f-4dac-8c4f-5357c62f0350">
Could you please let me know if there are any issues with my settings?

I notice that "_applySpriteFrame" has been marked as deprecated
could this be causing the issue?

I would appreciate a prompt response. Thank you so much.

**Comment by saghoti** [comment]
I Fix it by adding super.onEnable() to the first line of onEnable() !

**Comment by Hyrmm** [comment]
> I Fix it by adding super.onEnable() to the first line of onEnable() !

i use the version of 3.5.2, there is haven't super.onEnable(), but the picture is displayed,What caused
